import 'package:flutter/material.dart';

/// Cores aproximadas, no estilo do mapa vanilla do Minecraft.
class BlockColors {
  static const Color unknown = Color(0xFF7B7B7B);
  static const Color empty = Color(0x00000000);

  static const Map<String, Color> _colors = {
    // --- Terreno natural ---
    'minecraft:grass_block': Color(0xFF7CB342),
    'minecraft:short_grass': Color(0xFF7CB342),
    'minecraft:tall_grass': Color(0xFF6B9E37),
    'minecraft:fern': Color(0xFF6B9E37),
    'minecraft:dirt': Color(0xFF8B6544),
    'minecraft:coarse_dirt': Color(0xFF7A5A3C),
    'minecraft:podzol': Color(0xFF5C4327),
    'minecraft:mycelium': Color(0xFF6E6470),
    'minecraft:stone': Color(0xFF888888),
    'minecraft:deepslate': Color(0xFF4C4C4C),
    'minecraft:granite': Color(0xFF9C7B6B),
    'minecraft:diorite': Color(0xFFBDBDBD),
    'minecraft:andesite': Color(0xFF8F8F8F),
    'minecraft:calcite': Color(0xFFE0E0D3),
    'minecraft:tuff': Color(0xFF6C6E64),
    'minecraft:dripstone_block': Color(0xFF8B7361),
    'minecraft:sand': Color(0xFFDED09B),
    'minecraft:red_sand': Color(0xFFB0592B),
    'minecraft:sandstone': Color(0xFFE0D3A0),
    'minecraft:gravel': Color(0xFF8E8A87),
    'minecraft:water': Color(0xFF3A5EE0),
    'minecraft:flowing_water': Color(0xFF3A5EE0),
    'minecraft:ice': Color(0xFFA6D3F2),
    'minecraft:frosted_ice': Color(0xFFA6D3F2),
    'minecraft:packed_ice': Color(0xFF9CC7EE),
    'minecraft:blue_ice': Color(0xFF74A6E8),
    'minecraft:snow': Color(0xFFF7F7F7),
    'minecraft:snow_layer': Color(0xFFF7F7F7),
    'minecraft:lava': Color(0xFFE25822),
    'minecraft:flowing_lava': Color(0xFFE25822),
    'minecraft:clay': Color(0xFF9FA3AC),
    'minecraft:farmland': Color(0xFF5C4327),
    'minecraft:bedrock': Color(0xFF2B2B2B),
    'minecraft:obsidian': Color(0xFF14101B),
    'minecraft:crying_obsidian': Color(0xFF200D3C),
    'minecraft:netherrack': Color(0xFF723A3A),
    'minecraft:nether_wart_block': Color(0xFF7A1F1F),
    'minecraft:soul_sand': Color(0xFF4C3A2E),
    'minecraft:soul_soil': Color(0xFF4A3A2C),
    'minecraft:crimson_nylium': Color(0xFF9C2E2E),
    'minecraft:warped_nylium': Color(0xFF149C8A),
    'minecraft:end_stone': Color(0xFFDDDC9A),
    'minecraft:end_stone_bricks': Color(0xFFE3E2A8),
    'minecraft:magma': Color(0xFF8A3B1E),
    'minecraft:glowstone': Color(0xFFE7B75A),
    'minecraft:sea_lantern': Color(0xFFC8DCDA),
    'minecraft:prismarine': Color(0xFF5FA997),
    'minecraft:prismarine_bricks': Color(0xFF63B0A0),
    'minecraft:dark_prismarine': Color(0xFF376657),

    // --- Folhas e madeira natural ---
    'minecraft:oak_leaves': Color(0xFF4C7A2E),
    'minecraft:spruce_leaves': Color(0xFF2E5A2E),
    'minecraft:birch_leaves': Color(0xFF5D8A45),
    'minecraft:jungle_leaves': Color(0xFF3D7A2E),
    'minecraft:acacia_leaves': Color(0xFF5A8A3E),
    'minecraft:dark_oak_leaves': Color(0xFF3A5A28),
    'minecraft:mangrove_leaves': Color(0xFF3F7A32),
    'minecraft:cherry_leaves': Color(0xFFE897C1),
    'minecraft:azalea_leaves': Color(0xFF4C7A2E),

    // --- Madeiras (construcao) ---
    'minecraft:oak_log': Color(0xFF6B5335),
    'minecraft:oak_planks': Color(0xFFB08A5A),
    'minecraft:spruce_log': Color(0xFF4A3823),
    'minecraft:spruce_planks': Color(0xFF7A5A34),
    'minecraft:birch_log': Color(0xFFD9D0BD),
    'minecraft:birch_planks': Color(0xFFC8B37A),
    'minecraft:jungle_log': Color(0xFF6E5136),
    'minecraft:jungle_planks': Color(0xFFB1875A),
    'minecraft:acacia_log': Color(0xFF6D5142),
    'minecraft:acacia_planks': Color(0xFFB0603A),
    'minecraft:dark_oak_log': Color(0xFF3E2E1D),
    'minecraft:dark_oak_planks': Color(0xFF4F3623),
    'minecraft:mangrove_log': Color(0xFF7A3A38),
    'minecraft:mangrove_planks': Color(0xFF7C3F35),
    'minecraft:cherry_log': Color(0xFFB6876C),
    'minecraft:cherry_planks': Color(0xFFE5B6A6),
    'minecraft:bamboo_planks': Color(0xFFC9A227),
    'minecraft:crimson_stem': Color(0xFF8C4A6C),
    'minecraft:crimson_planks': Color(0xFF944156),
    'minecraft:warped_stem': Color(0xFF3E8E85),
    'minecraft:warped_planks': Color(0xFF3B8383),
    'minecraft:bookshelf': Color(0xFF98783E),

    // --- Pedras lapidadas e tijolos ---
    'minecraft:cobblestone': Color(0xFF7A7A7A),
    'minecraft:mossy_cobblestone': Color(0xFF6B7A5E),
    'minecraft:stone_bricks': Color(0xFF7D7D7D),
    'minecraft:mossy_stone_bricks': Color(0xFF6E7A5F),
    'minecraft:cracked_stone_bricks': Color(0xFF767676),
    'minecraft:chiseled_stone_bricks': Color(0xFF7D7D7D),
    'minecraft:polished_granite': Color(0xFF9C6E5A),
    'minecraft:polished_diorite': Color(0xFFC6C6C6),
    'minecraft:polished_andesite': Color(0xFF888E88),
    'minecraft:deepslate_bricks': Color(0xFF3F3F42),
    'minecraft:deepslate_tiles': Color(0xFF373739),
    'minecraft:polished_deepslate': Color(0xFF484849),
    'minecraft:cobbled_deepslate': Color(0xFF484848),
    'minecraft:brick_block': Color(0xFF9A5236),
    'minecraft:bricks': Color(0xFF9A5236),
    'minecraft:nether_bricks': Color(0xFF2C1518),
    'minecraft:red_nether_bricks': Color(0xFF4B0E0E),
    'minecraft:quartz_block': Color(0xFFECE3D7),
    'minecraft:smooth_quartz': Color(0xFFECE3D7),
    'minecraft:chiseled_quartz_block': Color(0xFFE9E1D4),
    'minecraft:quartz_pillar': Color(0xFFE9E1D4),
    'minecraft:purpur_block': Color(0xFFA97BA8),
    'minecraft:purpur_pillar': Color(0xFFA97BA8),

    // --- Metais e minerais ---
    'minecraft:iron_block': Color(0xFFD8D8D8),
    'minecraft:gold_block': Color(0xFFF9E259),
    'minecraft:diamond_block': Color(0xFF6EE8DA),
    'minecraft:emerald_block': Color(0xFF3BBA6C),
    'minecraft:lapis_block': Color(0xFF25469C),
    'minecraft:redstone_block': Color(0xFFA91A0A),
    'minecraft:netherite_block': Color(0xFF453F3F),
    'minecraft:copper_block': Color(0xFFC06E4F),
    'minecraft:exposed_copper': Color(0xFF9A7962),
    'minecraft:weathered_copper': Color(0xFF6C9270),
    'minecraft:oxidized_copper': Color(0xFF4E8F76),
    'minecraft:coal_block': Color(0xFF1A1A1A),

    // --- Vidro ---
    'minecraft:glass': Color(0xFFD0EAF0),
    'minecraft:glass_pane': Color(0xFFD0EAF0),
    'minecraft:tinted_glass': Color(0xFF2C2836),

    // --- Lã (16 cores) ---
    'minecraft:white_wool': Color(0xFFE9ECEC),
    'minecraft:orange_wool': Color(0xFFF9801D),
    'minecraft:magenta_wool': Color(0xFFC74EBD),
    'minecraft:light_blue_wool': Color(0xFF3AB3DA),
    'minecraft:yellow_wool': Color(0xFFFED83D),
    'minecraft:lime_wool': Color(0xFF80C71F),
    'minecraft:pink_wool': Color(0xFFF38BAA),
    'minecraft:gray_wool': Color(0xFF474F52),
    'minecraft:light_gray_wool': Color(0xFF9D9D97),
    'minecraft:cyan_wool': Color(0xFF169C9C),
    'minecraft:purple_wool': Color(0xFF8932B8),
    'minecraft:blue_wool': Color(0xFF3C44AA),
    'minecraft:brown_wool': Color(0xFF835432),
    'minecraft:green_wool': Color(0xFF5E7C16),
    'minecraft:red_wool': Color(0xFFB02E26),
    'minecraft:black_wool': Color(0xFF1D1D21),

    // --- Concreto (16 cores, mais saturado que a la) ---
    'minecraft:white_concrete': Color(0xFFCFD5D6),
    'minecraft:orange_concrete': Color(0xFFE06101),
    'minecraft:magenta_concrete': Color(0xFFA9309F),
    'minecraft:light_blue_concrete': Color(0xFF2389C7),
    'minecraft:yellow_concrete': Color(0xFFF0AF15),
    'minecraft:lime_concrete': Color(0xFF5EA918),
    'minecraft:pink_concrete': Color(0xFFD5658F),
    'minecraft:gray_concrete': Color(0xFF373A3E),
    'minecraft:light_gray_concrete': Color(0xFF7E7F76),
    'minecraft:cyan_concrete': Color(0xFF157788),
    'minecraft:purple_concrete': Color(0xFF64209C),
    'minecraft:blue_concrete': Color(0xFF2D2F8F),
    'minecraft:brown_concrete': Color(0xFF603C20),
    'minecraft:green_concrete': Color(0xFF495B24),
    'minecraft:red_concrete': Color(0xFF8E2121),
    'minecraft:black_concrete': Color(0xFF080A0F),

    // --- Terracota (16 cores + natural, tom terroso) ---
    'minecraft:terracotta': Color(0xFF985F49),
    'minecraft:white_terracotta': Color(0xFFD1B0A5),
    'minecraft:orange_terracotta': Color(0xFFA25A2E),
    'minecraft:magenta_terracotta': Color(0xFF95536B),
    'minecraft:light_blue_terracotta': Color(0xFF6E7F92),
    'minecraft:yellow_terracotta': Color(0xFFC5981F),
    'minecraft:lime_terracotta': Color(0xFF6C7833),
    'minecraft:pink_terracotta': Color(0xFFA85453),
    'minecraft:gray_terracotta': Color(0xFF3A2A25),
    'minecraft:light_gray_terracotta': Color(0xFF876A62),
    'minecraft:cyan_terracotta': Color(0xFF575F5E),
    'minecraft:purple_terracotta': Color(0xFF764656),
    'minecraft:blue_terracotta': Color(0xFF4A3C5B),
    'minecraft:brown_terracotta': Color(0xFF4D3324),
    'minecraft:green_terracotta': Color(0xFF4C5227),
    'minecraft:red_terracotta': Color(0xFF8A4433),
    'minecraft:black_terracotta': Color(0xFF251710),

    // --- Vidro colorido (tons pastel translucidos) ---
    'minecraft:white_stained_glass': Color(0xFFE6E6E6),
    'minecraft:orange_stained_glass': Color(0xFFE38A2E),
    'minecraft:magenta_stained_glass': Color(0xFFC96BC4),
    'minecraft:light_blue_stained_glass': Color(0xFF71B4D9),
    'minecraft:yellow_stained_glass': Color(0xFFE6D33B),
    'minecraft:lime_stained_glass': Color(0xFF9BD121),
    'minecraft:pink_stained_glass': Color(0xFFEBA0B5),
    'minecraft:gray_stained_glass': Color(0xFF5B6164),
    'minecraft:light_gray_stained_glass': Color(0xFFA9A9A3),
    'minecraft:cyan_stained_glass': Color(0xFF3AAFAF),
    'minecraft:purple_stained_glass': Color(0xFF9C4FC4),
    'minecraft:blue_stained_glass': Color(0xFF5761C2),
    'minecraft:brown_stained_glass': Color(0xFF9A6D45),
    'minecraft:green_stained_glass': Color(0xFF7C9A3C),
    'minecraft:red_stained_glass': Color(0xFFC44A3F),
    'minecraft:black_stained_glass': Color(0xFF3A3A3E),
  };

  static Color forBlock(String blockName) {
    if (blockName.isEmpty) return empty;
    return _colors[blockName] ?? unknown;
  }
}
